### PR TITLE
Fixed typo asnychronous => asynchronous

### PR DESCRIPTION
**Pull request by mickaelandrieu**
## Proposed changes

Only fix a typo in Issue template.
## Types of changes

What types of changes does your code introduce to WebdriverIO?
_Put an `x` in the boxes that apply_
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- [ ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
## Further comments

It's a typo, c'mon :)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Thanks

**Comment by mickaelandrieu** [comment]
:D I should close this one ;)

**Comment by christian-bromann** [comment]
Ohh I was wondering why I get two similar PRs and why I couldn't merge this one 😆

**Comment by mickaelandrieu** [comment]
@christian-bromann yeah, I made the pull request to the "bad" place first, sorry!

Also, if you have time of course, can you take a look to my [question](https://github.com/webdriverio/webdriverio/issues/1304) ? We use webdriver.io to test PrestaShop and we are happy with :)

**Pull request closed without merging**
